language: android
jdk: oraclejdk7
sudo: false

# Android components.
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-25
    - extra-android-m2repository

# Emulator Management: Create, Start and Wait.
before_script:
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./ci/tests.sh
	
after_success:
  - ./ci/deploy.sh

notifications:
 email: false
	
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

